package facebook_TC;

import java.util.List;

import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.support.ui.Select;
import org.testng.annotations.Test;

public class fb_try {
  @Test
  public static void facebook() throws InterruptedException {
	System.setProperty("webdriver.chrome.driver", "C:\\Users\\jatiny\\Downloads\\chromedriver_win32 (1)\\chromedriver.exe");
			
			WebDriver driver = new ChromeDriver();
			driver.manage().window().maximize();
			//driver.get("https://www.facebook.com");
			//driver.findElement(By.linkText("Create New Account")).click();
			Thread.sleep(3000);
			driver.get("https://www.facebook.com/reg");
			String title = driver.getTitle();
			System.out.println(title);
			driver.findElement(By.xpath("//input[contains(@name,'irst')]")).sendKeys("first");
			Thread.sleep(1000);
			driver.findElement(By.name("lastname")).sendKeys("last");
			Thread.sleep(1000);
			driver.findElement(By.name("reg_email__")).sendKeys("first_last_@facebook.com");
			Thread.sleep(1000);
			driver.findElement(By.name("reg_email_confirmation__")).sendKeys("first_last_@facebook.com");
			Thread.sleep(1000, 3);
			driver.findElement(By.name("reg_passwd__")).sendKeys("autogenerated");
			Thread.sleep(1000);
			WebElement day = driver.findElement(By.id("day"));
			
			WebElement month = driver.findElement(By.id("month"));
			
			
			WebElement year = driver.findElement(By.id("year"));
			Select dd = new Select(day);
			Select yy = new Select(year);
			Select mm = new Select(month);
			dd.selectByValue("3");
			mm.selectByIndex(10);
			yy.selectByValue("1998");
			Thread.sleep(5000);
			driver.findElement(By.xpath("//input[@value=\"1\"]")).click();
			Thread.sleep(3000);
			List<WebElement> gender = driver.findElements(By.name("sex"));
			int size = gender.size();
			for(int i = 0 ; i<size; i++) {
				String txt = gender.get(i).getText();
				System.out.println(txt);
				gender.get(i).click();
				Thread.sleep(1000);
				
			}
			Thread.sleep(3000);
			gender.get(1).click();
			
			Thread.sleep(2000);
			driver.close();
			
		}
}
